### ISSUE TITLE
Return other queues besides ranked

### ISSUE THREAD

**Issue by stradivari96** [mortdogged/backend#27]

**Comment by alvarooquintana** [comment]
podrias especificarme un poco mejor esto?

**Comment by stradivari96** [comment]
habría que buscar una manera de devolver también la info de otras colas, no sólo ranked.

prueba este summoner:
```
NEPvH9JOgTg4qY19khiQzQdO_5QeVL6_KYUVnp3iQaM_nZU
```
en este endpoint
https://developer.riotgames.com/apis#tft-league-v1/GET_getLeagueEntriesForSummoner

En el modelo `profile` pondría un array `other_leagues` con esa info
